general:
  # Commands to run when the WM has started. This is useful for running a
  # script or launching another application.
  # Example: The below command launches Zebar.
  startup_commands: ['shell-exec zebar']

  # Commands to run just before the WM is shutdown.
  # Example: The below command kills Zebar.
  shutdown_commands: ['shell-exec taskkill /IM zebar.exe /F']

  # Commands to run after the WM config is reloaded.
  config_reload_commands: []

  # Whether to automatically focus windows underneath the cursor.
  focus_follows_cursor: true

  # Whether to switch back and forth between the previously focused
  # workspace when focusing the current workspace.
  toggle_workspace_on_refocus: false

  cursor_jump:
    # Whether to automatically move the cursor on the specified trigger.
    enabled: true

    # Trigger for cursor jump:
    # - 'monitor_focus': Jump when focus changes between monitors.
    # - 'window_focus': Jump when focus changes between windows.
    trigger: 'window_focus'
gaps:
  # Whether to scale the gaps with the DPI of the monitor.
  scale_with_dpi: true

  # Gap between adjacent windows.
  inner_gap: '5px'

  # Gap between windows and the screen edge.
  outer_gap:
    top: '35px'
    right: '10px'
    bottom: '10px'
    left: '10px'

window_effects:
  # Visual effects to apply to the focused window.
  focused_window:
    # Highlight the window with a colored border.
    # ** Exclusive to Windows 11 due to API limitations.
    border:
      enabled: true
      color: '#8dbcff'


    # Remove the title bar from the window's frame. Note that this can
    # cause rendering issues for some applications.
    hide_title_bar:
      enabled: false

    # Change the corner style of the window's frame.
    # ** Exclusive to Windows 11 due to API limitations.
    corner_style:
      enabled: false
      # Allowed values: 'square', 'rounded', 'small_rounded'.
      style: 'square'


  # Visual effects to apply to non-focused windows.
  other_windows:
    border:
      enabled: true
      color: '#a1a1a1'
    hide_title_bar:
      enabled: false
    corner_style:
      enabled: false
      style: 'square'

window_behavior:
  # New windows are created in this state whenever possible.
  # Allowed values: 'tiling', 'floating'.
  initial_state: 'tiling'

  # Sets the default options for when a new window is created. This also
  # changes the defaults for when the state change commands, like
  # `set-floating`, are used without any flags.
  state_defaults:
    floating:
      # Whether to center floating windows by default.
      centered: true

      # Whether to show floating windows as always on top.
      shown_on_top: false

    fullscreen:
      # Maximize the window if possible. If the window doesn't have a
      # maximize button, then it'll be fullscreen'ed normally instead.
      maximized: false

      # Whether to show fullscreen windows as always on top.
      shown_on_top: false

workspaces:
  - name: scratch 
    display_name: üìì
  - name: coms
    display_name: üì£ 
    bind_to_monitor: 0
    keep_alive: true
  - name: info
    display_name: üåç
    bind_to_monitor: 0
    keep_alive: true
  - name: "1"
    display_name: I 
  - name: "2"
    display_name: II 
  - name: "3"
    display_name: III 
  - name: "4"
    display_name: IV
  - name: "5"
    display_name: V
  - name: "6"
    display_name: VI
  - name: "7"
    display_name: VII
  - name: "8"
    display_name: IIX 
  - name: "9"
    display_name: IX
  - name: "0"
    display_name: X
 

window_rules:
  - commands: ['ignore']
    match:
      # Ignores any Zebar windows.
      - window_process: { equals: 'zebar' }

      - window_class: { regex: "#32770" }

      - window_process: { regex: "Taskmgr|ScreenClippingHost" }
      
      - window_class: { equals: "OperationStatusWindow" }

      - window_title: { equals: "Run" } # Win + R

      # Ignores picture-in-picture windows for browsers.  
      - window_title: { regex: '[Pp]icture.in.[Pp]icture' }
        window_class: { regex: 'Chrome_WidgetWin_1|MozillaDialogClass' }
      # Ignore rules for various 3rd-party apps.
      - window_process: { equals: 'PowerToys.PowerAccent' }
      - window_process: { equals: 'PowerToys' }
        window_class: { regex: 'HwndWrapper\[PowerToys\.PowerAccent.*?\]' }
      - window_process: { equals: 'PowerToys' }
        window_title: { regex: '.*? - Peek' }
      - window_process: { equals: 'Lively' }
        window_class: { regex: 'HwndWrapper' }

  - commands: ['move --workspace info']
    match:
      - window_process: { equals: "msedge" }
      - window_process: { equals: "brave" } 
      - window_process: { equals: "sumatrapdf" }
      - window_process: { equals: "gvim" }

  - commands: ['move --workspace coms']
    match:
      - window_process: { equals: "Logseq" }
      - window_process: { equals: "WhatsApp" }
      - window_process: { equals: "Messenger" }
      - window_process: { equals: "Spotify" }
      - window_process: { equals: "Microsof Teams" }

binding_modes:
  # When enabled, the focused window can be resized via arrow keys or HJKL.
  - name: 'resize'
    keybindings:
      - commands: ['resize --width -2%']
        bindings: ['h', 'left']
      - commands: ['resize --width +2%']
        bindings: ['l', 'right']
      - commands: ['resize --height +2%']
        bindings: ['k', 'up']
      - commands: ['resize --height -2%']
        bindings: ['j', 'down']
      # Press enter/escape to return to default keybindings.
      - commands: ['wm-disable-binding-mode --name resize']
        bindings: ['escape', 'enter']

  # When enabled, all keybindings are disabled except for alt+shift+p which
  # returns to default keybindings.
  - name: 'pause'
    keybindings:
      - commands: ['wm-disable-binding-mode --name pause']
        bindings: ['alt+shift+p']

keybindings:
  # Shift focus in a given direction.
  - commands: ['focus --direction left']
    bindings: ['alt+h', 'alt+left']
  - commands: ['focus --direction right']
    bindings: ['alt+l', 'alt+right']
  - commands: ['focus --direction up']
    bindings: ['alt+k', 'alt+up']
  - commands: ['focus --direction down']
    bindings: ['alt+j', 'alt+down']

  # Move focused window in a given direction.
  - commands: ['move --direction left']
    bindings: ['alt+shift+h', 'alt+shift+left']
  - commands: ['move --direction right']
    bindings: ['alt+shift+l', 'alt+shift+right']
  - commands: ['move --direction up']
    bindings: ['alt+shift+k', 'alt+shift+up']
  - commands: ['move --direction down']
    bindings: ['alt+shift+j', 'alt+shift+down']

  # Resize focused window by a percentage or pixel amount.
  - commands: ['resize --width -2%']
    bindings: ['alt+u']
  - commands: ['resize --width +2%']
    bindings: ['alt+p']
  - commands: ['resize --height +2%']
    bindings: ['alt+o']
  - commands: ['resize --height -2%']
    bindings: ['alt+i']

  # As an alternative to the resize keybindings above, resize mode enables
  # resizing via arrow keys or HJKL. The binding mode is defined above with
  # the name 'resize'.
  - commands: ['wm-enable-binding-mode --name resize']
    bindings: ['alt+r']

  # Disables all keybindings until alt+shift+p is pressed again.
  - commands: ['wm-enable-binding-mode --name pause']
    bindings: ['alt+shift+p']

  # Change tiling direction. This determines where new tiling windows will
  # be inserted.
  - commands: ['toggle-tiling-direction']
    bindings: ['alt+v']


  # Change the focused window to be floating.
  - commands: ['toggle-floating --centered']
    bindings: ['alt+shift+space']

  # Change the focused window to be tiling.
  - commands: ['toggle-tiling']
    bindings: ['alt+t']

  # Change the focused window to be fullscreen.
  - commands: ['toggle-fullscreen']
    bindings: ['alt+x']

  # Minimize focused window.
  - commands: ['toggle-minimized']
    bindings: ['alt+m']

  # Close focused window.
  - commands: ['close']
    bindings: ['alt+shift+x']

  # Kill GlazeWM process safely.
  - commands: ['wm-exit']
    bindings: ['alt+shift+z']

  # Re-evaluate configuration file.
  - commands: ['wm-reload-config']
    bindings: ['alt+shift+v']

  # Launch CMD terminal. Alternatively, use `shell-exec wt` or
  # `shell-exec %ProgramFiles%/Git/git-bash.exe` to start Windows
  # Terminal and Git Bash respectively.
  - commands: ['shell-exec C:\Users\johan\scoop\apps\wezterm\current\wezterm-gui.exe']
    bindings: ['alt+enter']

  # Browser.
  - commands: ['shell-exec C:\Users\johan\scoop\apps\firefox\current\firefox.exe']
    bindings: ['alt+b']

  # PDF Viewer
  - commands: ['shell-exec C:\Users\johan\scoop\apps\sioyek\current\sioyek.exe']
    bindings: ['alt+e']

  # Focus the next/previous workspace defined in `workspaces` config.
  - commands: ['focus --next-workspace']
    bindings: ['alt+c']
  - commands: ['focus --prev-workspace']
    bindings: ['alt+shift+c']

  # Focus the workspace that last had focus.
  - commands: ['focus --recent-workspace']
    bindings: ['alt+z']

  # Change focus to a workspace defined in `workspaces` config.
  - commands: ['focus --workspace info']
    bindings: ['alt+w']
  - commands: ['focus --workspace coms']
    bindings: ['alt+q']
  - commands: ['focus --workspace scratch']
    bindings: ['alt+oem_pipe']
  - commands: ['focus --workspace 1']
    bindings: ['alt+1']
  - commands: ['focus --workspace 2']
    bindings: ['alt+2']
  - commands: ['focus --workspace 3']
    bindings: ['alt+3']
  - commands: ['focus --workspace 4']
    bindings: ['alt+4']
  - commands: ['focus --workspace 5']
    bindings: ['alt+5']
  - commands: ['focus --workspace 6']
    bindings: ['alt+6']
  - commands: ['focus --workspace 7']
    bindings: ['alt+7']
  - commands: ['focus --workspace 8']
    bindings: ['alt+8']
  - commands: ['focus --workspace 9']
    bindings: ['alt+9']
  - commands: ['focus --workspace 0']
    bindings: ['alt+0']
  # Move the focused window's parent workspace to a monitor in a given
  # direction.
  - commands: ['move-workspace --direction left']
    bindings: ['alt+shift+a']
  - commands: ['move-workspace --direction right']
    bindings: ['alt+shift+f']
  - commands: ['move-workspace --direction up']
    bindings: ['alt+shift+d']
  - commands: ['move-workspace --direction down']
    bindings: ['alt+shift+s']

  # Move focused window to a workspace defined in `workspaces` config.
  - commands: ['move --workspace info']
    bindings: ['alt+shift+w']
  - commands: ['move --workspace coms']
    bindings: ['alt+shift+q']
  - commands: ['move --workspace scratch']
    bindings: ['alt+shift+oem_pipe']
  - commands: ['move --workspace 1']
    bindings: ['alt+shift+1']
  - commands: ['move --workspace 2']
    bindings: ['alt+shift+2']
  - commands: ['move --workspace 3']
    bindings: ['alt+shift+3']
  - commands: ['move --workspace 4']
    bindings: ['alt+shift+4']
  - commands: ['move --workspace 5']
    bindings: ['alt+shift+5']
  - commands: ['move --workspace 6']
    bindings: ['alt+shift+6']
  - commands: ['move --workspace 7']
    bindings: ['alt+shift+7']
  - commands: ['move --workspace 8']
    bindings: ['alt+shift+8']
  - commands: ['move --workspace 9']
    bindings: ['alt+shift+9'] 
  - commands: ['move --workspace 0']
    bindings: ['alt+shift+0']
